#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT

ripper=$(which ripper-tags)
if [ -x "$ripper" ] ; then
  ripper-tags --tag-relative --extra=q -R -f .git/tags.$$ --exclude=.git --exclude=.rsync_cache --exclude=node_modules --exclude=vendor/bundle
fi

ctags --append --tag-relative=yes -f .git/tags.$$

mv -f .git/tags.$$ .git/tags
