#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags -Rf .git/tags.$$
# https://github.com/tmm1/ripper-tags
# ripper-tags --tag-relative -R -f .git/tags.$$ --exclude=.git --exclude=.rsync_cache
mv .git/tags.$$ .git/tags
